apiVersion: apps/v1
kind: Deployment
metadata:
  name: edart-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edart-core
  template:
    metadata:
      labels:
        app: edart-core
    spec:
      containers:
        - name: edart-core
          image: vviisydh/edart-core:2
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: DATABASE_URL
              value: "${DB_URL}"
---
apiVersion: v1
kind: Service
metadata:
  name: edart-core-service
spec:
  selector:
    app: edart-core
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer
